# Generated by Django 4.0.4 on 2022-04-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheese',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
